name: "Pull Request"
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  lint-test:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          tools: composer, php-cs-fixer
      
      - name: "Install Dependencies"
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: "Run PHP-CS-Fixer"
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: "Run Tests"
        run: php artisan test
